In [10]:
import numpy as np
# ===== 作业1：数组创建与属性分析 =====
# 创建3x4的二维数组，元素为1到12
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# 1.1 打印数组属性
print("数组形状:", arr.shape)  # (3, 4)
print("数组维度:", arr.ndim)   # 2
print("数据类型:", arr.dtype)  # int32或int64

# 1.2 数组元素乘以2
arr_doubled = arr * 2
print("元素乘以2后的数组:\n", arr_doubled)

# 1.3 重塑为4x3
arr_reshaped = arr.reshape(4, 3)
print("重塑为4x3的数组:\n", arr_reshaped)

# ===== 作业2：数组索引与切片 =====
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]])

数组形状: (3, 4)
数组维度: 2
数据类型: int64
元素乘以2后的数组:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
重塑为4x3的数组:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [11]:
# 2.1 提取第2行所有元素（注意索引从0开始）
row_2 = array[1, :]
print("\n第2行所有元素:", row_2)  # [5 6 7 8]

# 2.2 提取第3列所有元素
col_3 = array[:, 2]
print("第3列所有元素:", col_3)  # [3 7 11 15]

# 2.3 提取子数组（第1-2行，第2-3列）
sub_array = array[0:2, 1:3]
print("子数组:\n", sub_array)  # [[2 3][6 7]]

# 2.4 将大于10的元素替换为0
array[array > 10] = 0
print("替换后的数组:\n", array)


第2行所有元素: [5 6 7 8]
第3列所有元素: [ 3  7 11 15]
子数组:
 [[2 3]
 [6 7]]
替换后的数组:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10  0  0]
 [ 0  0  0  0]]


In [12]:
# ===== 作业3：数组运算与广播 =====
# 创建数组A（3x2）和数组B（1x2）
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])
B = np.array([10, 20])

# 3.1 逐元素相加（广播）
add_result = A + B
print("\nA + B:\n", add_result)  # [[11 22][13 24][15 26]]

# 3.2 逐元素相乘（广播）
mul_result = A * B
print("A * B:\n", mul_result)  # [[10 40][30 80][50 120]]

# 3.3 计算A的每一行与B的点积
dot_result = np.dot(A, B)  # 或使用 A @ B
print("A每行与B的点积:", dot_result)  # [50 110 170]


A + B:
 [[11 22]
 [13 24]
 [15 26]]
A * B:
 [[ 10  40]
 [ 30  80]
 [ 50 120]]
A每行与B的点积: [ 50 110 170]
